/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author ACER
 */
public class saleProduct extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet res;
String query;
    /**
     * Creates new form saleProduct
     */
    public saleProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtadv = new javax.swing.JTextField();
        txtta = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtcompany = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        purchase = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        show = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtorder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdop = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255), 10));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Product name");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(190, 10, 120, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Advance");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(400, 140, 100, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Company");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 70, 80, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Price");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(400, 70, 80, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 130, 100, 40);
        jPanel3.add(txtadv);
        txtadv.setBounds(550, 140, 160, 30);

        txtta.setEnabled(false);
        jPanel3.add(txtta);
        txtta.setBounds(190, 290, 160, 30);

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel3.add(txtprice);
        txtprice.setBounds(550, 80, 160, 30);

        txtcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompanyActionPerformed(evt);
            }
        });
        jPanel3.add(txtcompany);
        txtcompany.setBounds(170, 80, 160, 30);

        calculate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        calculate.setForeground(new java.awt.Color(255, 0, 0));
        calculate.setText("CALCULATE");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel3.add(calculate);
        calculate.setBounds(310, 200, 130, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Balance");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(460, 290, 100, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Total Amount");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(60, 290, 130, 30);

        txtbal.setEnabled(false);
        jPanel3.add(txtbal);
        txtbal.setBounds(550, 290, 160, 30);
        jPanel3.add(txtqty);
        txtqty.setBounds(170, 140, 160, 30);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setLayout(null);

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel4.add(back);
        back.setBounds(240, 30, 150, 30);

        purchase.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        purchase.setForeground(new java.awt.Color(255, 0, 51));
        purchase.setText("SALE");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });
        jPanel4.add(purchase);
        purchase.setBounds(50, 30, 150, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(200, 340, 460, 80);

        jPanel3.add(combo);
        combo.setBounds(350, 10, 150, 30);

        show.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 51, 51));
        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel3.add(show);
        show.setBounds(550, 10, 110, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(60, 240, 780, 440);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Order No.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 30, 90, 30);
        jPanel2.add(txtorder);
        txtorder.setBounds(170, 30, 160, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Date of sale");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(410, 30, 140, 30);
        jPanel2.add(txtdop);
        txtdop.setBounds(550, 30, 160, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 120, 780, 90);

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SALE PRODUCT");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(250, 10, 400, 60);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 900, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaku\\OneDrive\\Pictures\\Screenshots\\Screenshot 2024-06-20 144229.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1, 70, 1340, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(916, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    combo.addItem("<--SELECT-->");
        try
    {
    int oid=0;
    
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
     con=DriverManager.getConnection("jdbc:odbc:stock");
     stmt=con.createStatement();
    
    //To add data into combo box
    
     query="select * from purchasetable";
     res=stmt.executeQuery(query);
    while(res.next())
    {
        combo.addItem(res.getString("ppname"));
       // oid=Integer.parseInt(res.getString(1));
       // pid=Integer.parseInt(res.getString(3));
    
    }
    
      query="select * from saletable";
     res=stmt.executeQuery(query);
    while(res.next())
    {
       
        oid=Integer.parseInt(res.getString(1));
       // pid=Integer.parseInt(res.getString(3));
    
    }
    
     query="select * from saletable";
     res=stmt.executeQuery(query);
    while(res.next())
    {
        
        oid=Integer.parseInt(res.getString(1));
       
    
    }
    
     DateFormat df= new SimpleDateFormat("dd-MMM-yyyy");
            java.util.Date dt=new java.util.Date();
            txtdop.setText(String.valueOf((df.format(dt))));
            txtdop.setEnabled(false);
    txtorder.setText(String.valueOf(oid+1));
    
    txtorder.setEnabled(false);
    }
catch(Exception ex)
{}
    }//GEN-LAST:event_formWindowActivated

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompanyActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        int price,qty,adv,tamt,bal,x,y;
        price=Integer.parseInt(txtprice.getText());
        qty=Integer.parseInt(txtqty.getText());
        adv=Integer.parseInt(txtadv.getText());
        x=price*qty;
        txtta.setText(String.valueOf(x));
        y=x-adv;
        txtbal.setText(String.valueOf(y));

    }//GEN-LAST:event_calculateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        // TODO add your handling code here:
        try
        {
            String pname,pcom,pod;
            int odr,pid,price,qty,adv,tamt,bal;
            odr=Integer.parseInt(txtorder.getText());
            pod=txtdop.getText();

            price=Integer.parseInt(txtprice.getText());
            qty=Integer.parseInt(txtqty.getText());
            adv=Integer.parseInt(txtadv.getText());
            tamt=Integer.parseInt(txtta.getText());
            bal=Integer.parseInt(txtbal.getText());
            pname=combo.getSelectedItem().toString();
            pcom=txtcompany.getText();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:stock");
            stmt=con.createStatement();
            String query="Insert into saletable values("+odr+",'"+pod+"','"+pname+"','"+pcom+"',"+price+","+qty+","+adv+","+tamt+","+bal+")";
            stmt.executeUpdate(query);
            query="select * from stock where pname='"+pname+"'";
            res=stmt.executeQuery(query);
            if(res.next())
            {
                int q,totalqty;
                q=Integer.parseInt(res.getString("qty"));
              
                if(q<qty)
                    JOptionPane.showMessageDialog(null, "invalid quantity");
                else
                {
                totalqty=q-qty;

                query="update stock set qty="+totalqty+" where pname='"+pname+"'";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"Successfully sold");
                          
                txtcompany.setText("");
                txtprice.setText("");
                txtqty.setText("");
                txtadv.setText("");
                txtta.setText("");
                txtbal.setText("");
                }
            }
                
        }catch(Exception e)

        {JOptionPane.showMessageDialog(null, e.getMessage());}

    }//GEN-LAST:event_purchaseActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
         try
        {
            String pname=(combo.getSelectedItem().toString());
             query="select * from purchasetable where ppname='"+pname+"'";
           ResultSet res=stmt.executeQuery(query);
           res.next();
           txtcompany.setText(res.getString("pcompany"));
           txtprice.setText(res.getString("pprice"));
         //  txtqty.setText(res.getString("pquentity"));
           //txtadv.setText(res.getString("padvance"));
         }
        catch (Exception e)
        {JOptionPane.showMessageDialog(null, e.getMessage());}
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saleProduct().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton calculate;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton purchase;
    private javax.swing.JButton show;
    private javax.swing.JTextField txtadv;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txtcompany;
    private javax.swing.JTextField txtdop;
    private javax.swing.JTextField txtorder;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtta;
    // End of variables declaration//GEN-END:variables
}
